### ISSUE TITLE
Using 5 letter stations doesn't work

### ISSUE THREAD

**Issue by Donavin97** [jakewalter/easyQuake#1]
Hello, first off I want to thank you for developing such a great earthquake detection system.
I do have an issue though.
How can I import 5 letter station codes?
Most of the stations I use have 5 letter station codes, but they are not handled correctly by the program.
For example in the sta file the following happens:
  LBTB2500.91S02535.80E1148
  RTLG2121.71S02112.94E1198
How ever the second station should be GRTLG.
Any help or suggestions?
Thanks.

**Comment by jakewalter** [comment]
Some location programs truncate 5 letter stations into 4 so there is a part of the code that makes the station only 4 letters. Is there a particular reason or use case where you need to have the station output file with 5 characters?

**Comment by Donavin97** [comment]
Hi Jake. No, I thought that the stations won't function correctly.
But since the names are only truncated, no data is lost right?
Another question I have, what happens if I set machine to false?
Does the data have to be 1 day long, or can it be shorter, E.G. 1 hour?
Thanks.

**Comment by jakewalter** [comment]
The data can be shorter, as long as you organize the directory structure according to a timestamp. However, I recommend daily data as it makes things a little easier with the example scripts that are provided. We do have a very short event mode for trying out, if you like. If you set machine to False, then it will attempt to run a more traditional picker that is not very thoroughly tested. I suggest keeping the machine flag True and running it on tensorflow-gpu capable hardware (CUDA compatible NVIDIA card).

**Comment by Donavin97** [comment]
Thanks for the help, I can't set the machine mode to true, as I am using a PC that has no GPU at the moment. But very great app anyway, I'll definitely try it out again when I have acquired a GPU.
