### ISSUE TITLE
Error running the code

### ISSUE THREAD

**Issue by chenyu-lii** [jakewalter/easyQuake#2]
Hi authors of easyQuake,

I have encountered the following error when running the code, it seems to have some problem loading the model,
    **AttributeError: 'str' object has no attribute 'decode'**
After searching for the error on google, I ran the following command:
    **pip install 'h5py==2.10.0' --force-reinstall**
Then the program could run normally.

I guess there is something incompatible with the installed version of Keras and h5py, in case someone else have the same problem. 

Thank you,
Chenyu Li

**Comment by jakewalter** [comment]
Thanks for the note, I hope it helps anyone with that issue!
